export const FETCH_POSTS_REQUEST = "FETCH_POSTS_REQUEST";
export const FETCH_POSTS_SUCCESS = "FETCH_POSTS_SUCCESS";
export const FETCH_POSTS_FAILED = "FETCH_POSTS_FAILED";
export const RESET_POSTS = "RESET_POSTS";

export const FETCH_POST_REQUEST = "FETCH_POST_REQUEST";
export const FETCH_POST_SUCCESS = "FETCH_POST_SUCCESS";
export const FETCH_POST_FAILED = "FETCH_POST_FAILED";
export const RESET_POST = "RESET_POST";

export const FETCH_TAG_POSTS_REQUEST = "FETCH_TAG_POSTS_REQUEST";
export const FETCH_TAG_POSTS_SUCCESS = "FETCH_TAG_POSTS_SUCCESS";
export const FETCH_TAG_POSTS_FAILED = "FETCH_TAG_POSTS_FAILED";
export const RESET_TAG_POSTS = "RESET_TAG_POSTS";
